USE transportation_service;
DROP PROCEDURE IF EXISTS  UPDATE_CHO;

DELIMITER $$

CREATE PROCEDURE UPDATE_CHO
	(MA_KIEN_HANG INT,
    MA_CHUYEN_XE INT,
    MA_KIEN_HANG_MOI INT,
    MA_CHUYEN_XE_MOI INT) 
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;
    
	START TRANSACTION;
    
	CALL DELETE_CHO_NOT_COMMIT(MA_KIEN_HANG, MA_CHUYEN_XE);
    CALL INSERT_CHO_NOT_COMMIT(MA_KIEN_HANG_MOI, MA_CHUYEN_XE_MOI);
    
    COMMIT;
    SET AUTOCOMMIT = 1;
END $$

DELIMITER ;

