USE transportation_service;
DROP TRIGGER IF EXISTS  INSERT_KIEN_HANG_TRIGGER;
DELIMITER $$

CREATE TRIGGER INSERT_KIEN_HANG_TRIGGER AFTER INSERT ON KIEN_HANG
FOR EACH ROW
BEGIN
	UPDATE BIEN_BAN_GUI
	SET TONG_KHOI_LUONG = TONG_KHOI_LUONG + NEW.KHOI_LUONG
    WHERE BBGID = NEW.MA_BBG;
    
    UPDATE BIEN_BAN_NHAN
    SET TONG_KHOI_LUONG = TONG_KHOI_LUONG + NEW.KHOI_LUONG
    WHERE BBNID = NEW.MA_BBN;
END $$

DELIMITER ; 