USE transportation_service;
DROP PROCEDURE IF EXISTS  DELETE_CHO;

DELIMITER $$

CREATE PROCEDURE DELETE_CHO
	(MA_KIEN_HANG INT,
    MA_CHUYEN_XE INT)
BEGIN
	START TRANSACTION;
    
    CALL DELETE_CHO_NOT_COMMIT(MA_KIEN_HANG, MA_CHUYEN_XE);
    
    COMMIT;
    SET AUTOCOMMIT = 1;
END $$

DELIMITER ;

