USE transportation_service;
DROP FUNCTION IF EXISTS WEIGHT_OF_SHIP;

DELIMITER $$

CREATE FUNCTION WEIGHT_OF_SHIP
	(MA_CHUYEN_XE INT)
RETURNS DECIMAL(7,2)
READS SQL DATA
DETERMINISTIC
BEGIN
	RETURN (SELECT KHOI_LUONG_HIEN_TAI
			FROM CHUYEN_XE_LIEN_TINH 
			WHERE MA_CHUYEN = MA_CHUYEN_XE);
END $$

DELIMITER ;

