USE transportation_service;
DROP PROCEDURE IF EXISTS  DELETE_CHO_NOT_COMMIT;

DELIMITER $$

-- AFTER USE(i.e. COMMIT) MUST SET AUTOCOMMIT = 1
CREATE PROCEDURE DELETE_CHO_NOT_COMMIT
	(MA_KIEN_HANG INT,
    MA_CHUYEN_XE INT)
BEGIN
	SET AUTOCOMMIT = 0;
    
	IF (EXIST_PACKAGE_SHIP(MA_KIEN_HANG, MA_CHUYEN_XE)) THEN
		DELETE FROM CHO c 
		WHERE 	c.MA_KIEN_HANG = MA_KIEN_HANG AND
				c.MA_CHUYEN_XE = MA_CHUYEN_XE;
		
		UPDATE CHUYEN_XE_LIEN_TINH c
		SET SO_KIEN_HANG = SO_KIEN_HANG - 1,
			KHOI_LUONG_HIEN_TAI = KHOI_LUONG_HIEN_TAI - WEIGHT_OF_PACKAGE(MA_KIEN_HANG)
		WHERE c.MA_CHUYEN = MA_CHUYEN_XE;
	ELSE
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'Không tìm thấy kiện hàng-chuyến xe để xóa';
    END IF;
END $$

DELIMITER ;

