DROP PROCEDURE IF EXISTS FindReceiveDate;
DELIMITER //
CREATE PROCEDURE FindReceiveDate (GID INT, NID INT, NGAYGUI DATE)
BEGIN
	SELECT ID, NGAY_NHAN
	FROM KIEN_HANG JOIN BIEN_BAN_NHAN ON MA_BBN = BBNID
	WHERE KIEN_HANG.MA_NGUOI_NHAN = NID AND KIEN_HANG.MA_NGUOI_GUI = GID 
        AND MA_BBG IN (SELECT BBGID 
                       FROM BIEN_BAN_GUI 
                       WHERE NGAY_GUI = NGAYGUI) 
	ORDER BY ID;
END //
DELIMITER ;

DROP PROCEDURE IF EXISTS RevenueOfCustomer;
DELIMITER //
CREATE PROCEDURE RevenueOfCustomer (IN ID_KH INT, IN NAM YEAR, OUT RESULT INT)
BEGIN
	DECLARE phi_ng int;
    DECLARE phi_nn int;
	SELECT SUM(PHI_NOI_THANH) INTO phi_ng
    FROM KIEN_HANG JOIN BIEN_BAN_GUI ON MA_BBG = BBGID
    WHERE KIEN_HANG.MA_NGUOI_GUI = ID_KH AND NGAY_GUI LIKE CONCAT(NAM,'%');
    IF phi_ng IS NULL THEN
		SET phi_ng = 0;
	END IF;
    
    SELECT (SUM(PHI_NOI_THANH) + SUM(PHI_LIEN_TINH)) INTO phi_nn
    FROM KIEN_HANG JOIN BIEN_BAN_NHAN ON MA_BBN = BBNID
    WHERE KIEN_HANG.MA_NGUOI_NHAN = ID_KH AND NGAY_NHAN LIKE CONCAT(NAM,'%');
	IF phi_nn IS NULL THEN
		SET phi_nn = 0;
	END IF;
   
    set RESULT = phi_ng;
    set RESULT = RESULT + phi_nn;
END //

DELIMITER ;

--CALL FindReceiveDate(2,7,'2022/10/01');
--CALL RevenueOfCustomer(2,'2022',@RESULT);
--SELECT @RESULT;
