USE transportation_service;
DROP FUNCTION IF EXISTS EXIST_PACKAGE_SHIP;

DELIMITER $$

CREATE FUNCTION EXIST_PACKAGE_SHIP
	(MA_KIEN_HANG INT, MA_CHUYEN_XE INT)
RETURNS BOOLEAN
READS SQL DATA
DETERMINISTIC
BEGIN
    RETURN EXISTS (
					SELECT * FROM CHO c 
					WHERE 	c.MA_KIEN_HANG = MA_KIEN_HANG AND
							c.MA_CHUYEN_XE = MA_CHUYEN_XE);
END $$

DELIMITER ;

