USE transportation_service;
DROP FUNCTION IF EXISTS WEIGHT_OF_CONTAINER_OF_SHIP;

DELIMITER $$

CREATE FUNCTION WEIGHT_OF_CONTAINER_OF_SHIP
	(MA_CHUYEN_XE INT)
RETURNS INT
READS SQL DATA
DETERMINISTIC
BEGIN
    RETURN (SELECT TRONG_TAI
			FROM CHUYEN_XE_LIEN_TINH
			JOIN CONTAINER
			USING (MA_XE)
			WHERE MA_CHUYEN = MA_CHUYEN_XE);
END $$

DELIMITER ;

