USE transportation_service;
DROP FUNCTION IF EXISTS WEIGHT_OF_PACKAGE;

DELIMITER $$

CREATE FUNCTION WEIGHT_OF_PACKAGE
	(MA_KIEN_HANG INT)
RETURNS DECIMAL(4,1)
READS SQL DATA
DETERMINISTIC
BEGIN
	RETURN (SELECT KHOI_LUONG
			FROM KIEN_HANG
			WHERE ID = MA_KIEN_HANG);
END $$

DELIMITER ;

